import time
from math import sqrt

start_time = time.time()


def p045():
    """Triangular, pentagonal, and hexagonal

    Problem 45

    Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
    Triangle 	  	T_n=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
    Pentagonal 	  	P_n=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
    Hexagonal 	  	H_n=n(2n−1) 	  	1, 6, 15, 28, 45, ...

    It can be verified that T_285 = P_165 = H_143 = 40755.

    Find the next triangle number that is also pentagonal and hexagonal.
        """

    n = 286

    while True:
        t_n = n * (n + 1) // 2

        if is_pentagonal(t_n):
            if is_hexagonal(t_n):
                return t_n

        n += 1
        continue


def is_pentagonal(n):
    if sqrt(24 * n + 1) % 1 == 0:
        if (sqrt(24 * n + 1) + 1) % 6 == 0:
            return True

    return False


def is_hexagonal(n):
    if sqrt(8 * n + 1) % 1 == 0:
        if (sqrt(8 * n + 1) + 1) % 4 == 0:
            return True

    return False


print(p045())
print('Completed in', time.time() - start_time, 'seconds')
